name: pr
on: [pull_request]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    container: cypress/browsers:node12.13.0-chrome80-ff74
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v1

      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      # https://github.com/cypress-io/github-action
      - name: Cypress run 🧪
        uses: cypress-io/github-action@v1
        with:
          # let's go through the tests and generate all diffs
          env: failOnSnapshotDiff=false

      - name: Store snapshots 📸
        uses: actions/upload-artifact@v1
        with:
          name: snapshots
          path: cypress/snapshots

      - name: Set commit status 🖼
        run: |
          node ./scripts/set-gh-check.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
